AWSTemplateFormatVersion: 2010-09-09
Description: "vpc automation project"
Metadata: {}

Parameters: {}

Mappings: {}

Conditions: {}

Resources: 
  #Devserver
  DevVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: DevVPC


  #DevWebserver
  DevWebserverSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref DevVPC
      CidrBlock: 10.0.5.0/24
      Tags:
        - Key: Name
          Value: DevWebserverSubnet


         
 #DevWebserver
  DevAppserverSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1b
      VpcId: !Ref DevVPC
      CidrBlock: 10.0.10.0/24
      Tags:
        - Key: Name
          Value: DevAppserverSubnet



    #DevWebserver
  DevDatabaseSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1c
      VpcId: !Ref DevVPC
      CidrBlock: 10.0.20.0/24
      Tags:
        - Key: Name
          Value: DevDatabaseSubnet  
          
              
Outputs: {}